# Build Workflow

name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
      paths-ignore:
          - 'README.md'
          - '.github/**'
          - '.editorconfig'
          - 'CODE_OF_CONDUCT.md'
          - 'CONTRIBUTING.md'
          - 'SECURITY.md'
          - 'LICENSE'
          - '.gitattributes'
          - '.gitignore'

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: CI/CD build on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
            add-job-summary-as-pr-comment: always
            add-job-summary: always
            build-scan-publish: true
            build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
            build-scan-terms-of-use-agree: "yes"
            gradle-home-cache-cleanup: true
            validate-wrappers: true
            cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/modern' }}


      - name: Build
        run: ./gradlew build

      - name: Upload stage0 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stage0-artifacts
          path: stage0/build/libs/

      - name: Upload stage1 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stage1-artifacts
          path: stage1/build/libs/
